.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH scanr-config-show 1  "scanr-config-show " 
.SH NAME
scanr\-config\-show \- Show the merged configuration
.SH SYNOPSIS
\fBscanr\-config\-show\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show the merged configuration
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
