.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH scanr-output-cat 1  "scanr-output-cat " 
.SH NAME
scanr\-output\-cat \- Write the record as plain JSONL, decompressing it if needed
.SH SYNOPSIS
\fBscanr\-output\-cat\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFILE\fR> 
.SH DESCRIPTION
Write the record as plain JSONL, decompressing it if needed
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFILE\fR>

