.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH scanr-output-verify 1  "scanr-output-verify " 
.SH NAME
scanr\-output\-verify \- Check a scan record for integrity and completeness
.SH SYNOPSIS
\fBscanr\-output\-verify\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFILE\fR> 
.SH DESCRIPTION
Check a scan record for integrity and completeness
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFILE\fR>

