.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH scanr-config-validate 1  "scanr-config-validate " 
.SH NAME
scanr\-config\-validate \- Check configuration without running anything
.SH SYNOPSIS
\fBscanr\-config\-validate\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Check configuration without running anything
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
