.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH scanr-config-path 1  "scanr-config-path " 
.SH NAME
scanr\-config\-path \- Show which configuration files were discovered
.SH SYNOPSIS
\fBscanr\-config\-path\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show which configuration files were discovered
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
