.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH scanr-transport-show 1  "scanr-transport-show " 
.SH NAME
scanr\-transport\-show \- Show one transport\*(Aqs resolved settings
.SH SYNOPSIS
\fBscanr\-transport\-show\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Show one transport\*(Aqs resolved settings
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>

