.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH scanr-output-remainder 1  "scanr-output-remainder " 
.SH NAME
scanr\-output\-remainder \- Print targets that were not fully probed, for feeding back into \-\-targets
.SH SYNOPSIS
\fBscanr\-output\-remainder\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFILE\fR> 
.SH DESCRIPTION
Print targets that were not fully probed, for feeding back into \-\-targets
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFILE\fR>

