//! The compatibility corpus: `tests/compat/` holds one record per product workflow, the
//! exact output every reader must produce for it, and the `config init` template of
//! every release — and these tests hold the current binary to all of it.
//!
//! This is the promise in `docs/stability.md` made checkable. A change that alters how
//! an old record reads back, or refuses a config that once validated, fails here before
//! it ships. Records from older schema versions are generated by the release binaries
//! themselves, so "reads version 1" is a fact about a file 0.2.2 wrote, not a belief.
//!
//! Regenerating (adds scenarios or refreshes expectations; review the diff):
//!
//! ```console
//! SCANR_COMPAT_BIN_0_2_2=/path/to/scanr-0.2.2 \
//! SCANR_COMPAT_BIN_0_3_0=/path/to/scanr-0.3.0 \
//! SCANR_COMPAT_BIN_0_4_0=/path/to/scanr-0.4.0 \
//!   cargo test --test compat -- --ignored regenerate_compat_corpus
//! ```

use std::path::{Path, PathBuf};
use std::process::{Command, Output, Stdio};
use std::time::Duration;

use serde_json::Value;

const BIN: &str = env!("CARGO_BIN_EXE_scanr");

fn corpus() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/compat")
}

/// Readers whose output is pinned, as `(expected file, arguments before the record)`.
///
/// Run from the scenario directory against the relative name `record.*`, so no absolute
/// path reaches the output. Colour is off and `read.toml` disables `/etc/services`, so
/// service labels come from the binary alone and the output is the same on every host.
const READERS: &[(&str, &[&str])] = &[
    ("verify.txt", &["output", "verify"]),
    ("summarize.txt", &["output", "summarize"]),
    (
        "summarize.json",
        &["output", "summarize", "--format", "json"],
    ),
    ("results.txt", &["output", "results"]),
    ("results.json", &["output", "results", "--format", "json"]),
    (
        "results-open.list",
        &["output", "results", "--states", "open", "--format", "list"],
    ),
    (
        "results-open.nmap",
        &["output", "results", "--states", "open", "--format", "nmap"],
    ),
    ("remainder.txt", &["output", "remainder"]),
];

/// Every scenario, with the claim it exists to prove. `tests/compat/README.md` is
/// written from this table.
const SCENARIOS: &[(&str, &str)] = &[
    (
        "direct-mixed",
        "a direct scan records open, closed and filtered (spans on, gzip); verify passes and remainder reports it complete",
    ),
    (
        "direct-rows",
        "the same scan as one row per probe, plain JSONL (`--no-spans --no-compress`); readers give the same answers",
    ),
    (
        "socks5-full",
        "through a faithful SOCKS5 proxy a refused port is `closed` with `source: proxy_reply`",
    ),
    (
        "socks5-open-only",
        "through a proxy that collapses failures, non-open results are `error`, never a fabricated `closed`",
    ),
    (
        "http-proxy",
        "through an HTTP CONNECT proxy the transport is `open_only` by construction and non-open results carry the status line",
    ),
    (
        "chain-http-socks5",
        "a chain of http → socks5 records both hops with their protocols and keeps the SOCKS5 exit's `full` fidelity",
    ),
    (
        "pool",
        "a pool assigns each endpoint to a member deterministically and records `via` on every result",
    ),
    (
        "banner-tls",
        "a greeting service is recorded verbatim and never probed; a silent TLS service yields certificate, cipher and ALPN under `--tls`",
    ),
    (
        "interrupted",
        "Ctrl-C leaves a finalised record whose counts account for every planned probe (completed + abandoned + not_started)",
    ),
    (
        "resumed",
        "`output remainder | run --pairs -` probes exactly what was outstanding and links the new record to the old via `resumed_from`",
    ),
    (
        "v1-0.2.2",
        "a schema_version 1 record written by the 0.2.2 release reads back through every reader of the current binary",
    ),
];

fn run_with(bin: &str, cwd: &Path, args: &[&str]) -> Output {
    Command::new(bin)
        .args(args)
        .current_dir(cwd)
        .env("NO_COLOR", "1")
        .env("XDG_CONFIG_HOME", cwd.join(".xdg"))
        .stdin(Stdio::null())
        .output()
        .expect("scanr should run")
}

fn run(cwd: &Path, args: &[&str]) -> Output {
    run_with(BIN, cwd, args)
}

fn out(o: &Output) -> String {
    String::from_utf8_lossy(&o.stdout).into_owned()
}

fn err(o: &Output) -> String {
    String::from_utf8_lossy(&o.stderr).into_owned()
}

fn code(o: &Output) -> i32 {
    o.status.code().unwrap_or(-1)
}

fn record_in(dir: &Path) -> PathBuf {
    let mut names: Vec<PathBuf> = std::fs::read_dir(dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| {
            let n = p.file_name().unwrap_or_default().to_string_lossy();
            n.starts_with("scan-") && !n.ends_with(".partial")
        })
        .collect();
    names.sort();
    names.pop().expect("a finalised record")
}

fn record_file(scenario: &Path) -> PathBuf {
    for n in ["record.jsonl.gz", "record.jsonl"] {
        if scenario.join(n).exists() {
            return scenario.join(n);
        }
    }
    panic!("{} has no record", scenario.display());
}

/// The reader invocation for one pinned output, run from the scenario directory.
fn read(scenario: &Path, args: &[&str]) -> Output {
    let record = record_file(scenario);
    let name = record.file_name().unwrap().to_str().unwrap();
    let cfg = corpus().join("read.toml");
    let mut full: Vec<&str> = vec!["--config", cfg.to_str().unwrap(), "--no-color"];
    full.extend_from_slice(args);
    full.push(name);
    run(scenario, &full)
}

fn scenario_dirs() -> Vec<PathBuf> {
    let mut dirs: Vec<PathBuf> = std::fs::read_dir(corpus().join("records"))
        .expect("tests/compat/records exists")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.is_dir())
        .collect();
    dirs.sort();
    dirs
}

// ── the checks ────────────────────────────────────────────────────────────────

/// Every reader, on every record in the corpus, still produces exactly the pinned
/// output and exit code.
#[test]
fn every_corpus_record_reads_back_exactly_as_expected() {
    let dirs = scenario_dirs();
    assert!(
        dirs.len() >= SCENARIOS.len(),
        "corpus has {} scenarios, expected at least {}; regenerate it",
        dirs.len(),
        SCENARIOS.len()
    );
    let mut failures = Vec::new();
    for dir in &dirs {
        for (name, args) in READERS {
            let o = read(dir, args);
            let expected_out = std::fs::read_to_string(dir.join("expected").join(name))
                .unwrap_or_else(|e| panic!("{}/expected/{name}: {e}", dir.display()));
            let expected_code: i32 =
                std::fs::read_to_string(dir.join("expected").join(format!("{name}.code")))
                    .unwrap_or_else(|e| panic!("{}/expected/{name}.code: {e}", dir.display()))
                    .trim()
                    .parse()
                    .unwrap();
            if out(&o) != expected_out || code(&o) != expected_code {
                failures.push(format!(
                    "{}/{name}: exit {} (expected {}); stderr: {}\n--- expected ---\n{}--- actual ---\n{}",
                    dir.file_name().unwrap().to_string_lossy(),
                    code(&o),
                    expected_code,
                    err(&o).trim(),
                    expected_out,
                    out(&o)
                ));
            }
        }
    }
    assert!(
        failures.is_empty(),
        "{} reader outputs changed:\n\n{}",
        failures.len(),
        failures.join("\n\n")
    );
}

/// Both schema versions are in the corpus and read by this binary.
#[test]
fn the_corpus_covers_every_schema_version_this_build_reads() {
    let mut seen = std::collections::BTreeSet::new();
    for dir in scenario_dirs() {
        let o = read(&dir, &["output", "events"]);
        assert_eq!(code(&o), 0, "{}: {}", dir.display(), err(&o));
        let first: Value = serde_json::from_str(out(&o).lines().next().unwrap()).unwrap();
        assert_eq!(first["type"], "scan_started", "{}", dir.display());
        seen.insert(first["schema_version"].as_u64().unwrap());
    }
    let supported: std::collections::BTreeSet<u64> = scanr::output::SUPPORTED_SCHEMA_VERSIONS
        .iter()
        .map(|v| u64::from(*v))
        .collect();
    assert_eq!(
        seen, supported,
        "every readable schema version needs a record in the corpus"
    );
}

/// A `scanr.toml` written by any release's `config init` validates and plans under the
/// current binary: keys are never removed and their meaning never changes.
#[test]
fn every_prior_config_template_still_validates_and_plans() {
    let dir = corpus().join("configs");
    let mut files: Vec<PathBuf> = std::fs::read_dir(&dir)
        .expect("tests/compat/configs exists")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "toml"))
        .collect();
    files.sort();
    assert!(
        files.len() >= 4,
        "expected a template per release, found {}",
        files.len()
    );
    let tmp = tempfile::tempdir().unwrap();
    for f in files {
        let cfg = f.to_str().unwrap();
        let v = run(tmp.path(), &["--config", cfg, "config", "validate"]);
        assert_eq!(code(&v), 0, "{}: {}", f.display(), err(&v));
        let p = run(tmp.path(), &["--config", cfg, "plan", "internal-web"]);
        assert_eq!(code(&p), 0, "{}: {}", f.display(), err(&p));
        assert!(out(&p).contains("probes"), "{}", f.display());
    }
}

/// The scenario table and the directory agree, so a scenario cannot be added without
/// stating what it proves, or dropped without the table noticing.
#[test]
fn every_scenario_states_its_claim() {
    let on_disk: Vec<String> = scenario_dirs()
        .iter()
        .map(|d| d.file_name().unwrap().to_string_lossy().into_owned())
        .collect();
    let mut listed: Vec<String> = SCENARIOS.iter().map(|(n, _)| n.to_string()).collect();
    listed.sort();
    assert_eq!(on_disk, listed);
    let readme = std::fs::read_to_string(corpus().join("README.md")).expect("README.md");
    for (name, claim) in SCENARIOS {
        assert!(
            readme.contains(name) && readme.contains(claim),
            "README.md is stale for `{name}`"
        );
    }
}

// ── the generator ─────────────────────────────────────────────────────────────

fn open_port() -> (std::net::TcpListener, u16) {
    let l = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
    let p = l.local_addr().unwrap().port();
    let acc = l.try_clone().unwrap();
    std::thread::spawn(move || {
        for s in acc.incoming() {
            drop(s);
        }
    });
    (l, p)
}

fn greeting_port(greeting: &'static [u8]) -> (std::net::TcpListener, u16) {
    use std::io::Write;
    let l = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
    let p = l.local_addr().unwrap().port();
    let acc = l.try_clone().unwrap();
    std::thread::spawn(move || {
        for s in acc.incoming().flatten() {
            let _ = (&s).write_all(greeting);
        }
    });
    (l, p)
}

fn closed_port() -> u16 {
    let l = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
    let p = l.local_addr().unwrap().port();
    drop(l);
    p
}

fn install(name: &str, record: &Path) -> PathBuf {
    let dir = corpus().join("records").join(name);
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(dir.join("expected")).unwrap();
    let ext = if record.to_string_lossy().ends_with(".gz") {
        "record.jsonl.gz"
    } else {
        "record.jsonl"
    };
    std::fs::copy(record, dir.join(ext)).unwrap();
    for (out_name, args) in READERS {
        let o = read(&dir, args);
        let exit = code(&o);
        std::fs::write(dir.join("expected").join(out_name), o.stdout).unwrap();
        std::fs::write(
            dir.join("expected").join(format!("{out_name}.code")),
            format!("{exit}\n"),
        )
        .unwrap();
    }
    dir
}

fn scan(dir: &Path, args: &[&str]) -> PathBuf {
    let mut full = vec!["run", "--output-dir", "out", "-q"];
    full.extend_from_slice(args);
    let o = run(dir, &full);
    assert!(o.status.success(), "{args:?}: {}", err(&o));
    record_in(&dir.join("out"))
}

#[test]
#[ignore = "rewrites tests/compat; run deliberately and review the diff"]
fn regenerate_compat_corpus() {
    use scanr::testsupport::http::{Behavior as H, HttpFixture};
    use scanr::testsupport::socks5::{Behavior as S, Socks5Fixture};
    use scanr::testsupport::tls::{Behavior as T, TlsFixture};

    std::fs::create_dir_all(corpus().join("records")).unwrap();
    std::fs::create_dir_all(corpus().join("configs")).unwrap();
    std::fs::write(
        corpus().join("read.toml"),
        "# Used by tests/compat.rs when reading corpus records: labels from the binary only,\n\
         # so the pinned output is the same on every machine.\nversion = 1\n\n[defaults]\nuse_etc_services = false\n",
    )
    .unwrap();

    let (_o1, open1) = open_port();
    let (_o2, open2) = open_port();
    let closed1 = closed_port();
    let closed2 = closed_port();
    let mixed_ports = format!("{open1},{open2},{closed1},{closed2}");

    // 1–2. direct, both record forms. 192.0.2.1 is unroutable, so its ports are filtered.
    for (name, extra) in [
        ("direct-mixed", vec![]),
        ("direct-rows", vec!["--no-spans", "--no-compress"]),
    ] {
        let d = tempfile::tempdir().unwrap();
        let mut args = vec![
            "--targets",
            "127.0.0.1,192.0.2.1",
            "--ports",
            &mixed_ports,
            "--all",
            "--connect-timeout",
            "1s",
            "--seed",
            "1",
        ];
        args.extend(extra);
        let rec = scan(d.path(), &args);
        install(name, &rec);
    }

    // 3–4. SOCKS5, faithful and collapsing.
    let two_ports = format!("{open1},{closed1}");
    for (name, behavior, fidelity) in [
        ("socks5-full", S::Faithful, "fidelity = \"full\"\n"),
        ("socks5-open-only", S::Collapsing, ""),
    ] {
        let fx = Socks5Fixture::start(behavior);
        let d = tempfile::tempdir().unwrap();
        std::fs::write(
            d.path().join("scanr.toml"),
            format!(
                "version = 1\n[transports.lab]\ntype = \"socks5\"\naddress = \"{}\"\n{fidelity}",
                fx.addr()
            ),
        )
        .unwrap();
        let rec = scan(
            d.path(),
            &[
                "--transport",
                "lab",
                "--targets",
                "127.0.0.1",
                "--ports",
                &two_ports,
                "--all",
                "--seed",
                "2",
            ],
        );
        install(name, &rec);
    }

    // 5. HTTP CONNECT.
    {
        let fx = HttpFixture::start(H::Faithful);
        let d = tempfile::tempdir().unwrap();
        std::fs::write(
            d.path().join("scanr.toml"),
            format!(
                "version = 1\n[transports.corp]\ntype = \"http\"\naddress = \"{}\"\n",
                fx.addr()
            ),
        )
        .unwrap();
        let rec = scan(
            d.path(),
            &[
                "--transport",
                "corp",
                "--targets",
                "127.0.0.1",
                "--ports",
                &two_ports,
                "--all",
                "--seed",
                "3",
            ],
        );
        install("http-proxy", &rec);
    }

    // 6. A mixed chain.
    {
        let h = HttpFixture::start(H::Faithful);
        let s = Socks5Fixture::start(S::Faithful);
        let d = tempfile::tempdir().unwrap();
        std::fs::write(
            d.path().join("scanr.toml"),
            format!(
                "version = 1\n[transports.corp]\ntype = \"http\"\naddress = \"{}\"\n\
                 [transports.exit]\ntype = \"socks5\"\naddress = \"{}\"\nfidelity = \"full\"\n\
                 [transports.path]\ntype = \"chain\"\nhops = [\"corp\", \"exit\"]\n",
                h.addr(),
                s.addr()
            ),
        )
        .unwrap();
        let rec = scan(
            d.path(),
            &[
                "--transport",
                "path",
                "--targets",
                "127.0.0.1",
                "--ports",
                &two_ports,
                "--all",
                "--seed",
                "4",
            ],
        );
        install("chain-http-socks5", &rec);
    }

    // 7. A pool of two.
    {
        let a = Socks5Fixture::start(S::Faithful);
        let b = Socks5Fixture::start(S::Faithful);
        let d = tempfile::tempdir().unwrap();
        std::fs::write(
            d.path().join("scanr.toml"),
            format!(
                "version = 1\n[transports.a]\ntype = \"socks5\"\naddress = \"{}\"\nfidelity = \"full\"\n\
                 [transports.b]\ntype = \"socks5\"\naddress = \"{}\"\nfidelity = \"full\"\n\
                 [transports.spread]\ntype = \"pool\"\nmembers = [\"a\", \"b\"]\n",
                a.addr(),
                b.addr()
            ),
        )
        .unwrap();
        let rec = scan(
            d.path(),
            &[
                "--transport",
                "spread",
                "--targets",
                "127.0.0.1",
                "--ports",
                &mixed_ports,
                "--all",
                "--seed",
                "5",
            ],
        );
        install("pool", &rec);
    }

    // 8. Banner and TLS.
    {
        let (_g, smtp) = greeting_port(b"220 corpus.example ESMTP\r\n");
        let tls = TlsFixture::start(T::Tls12 { alpn: Some("h2") });
        let d = tempfile::tempdir().unwrap();
        let ports = format!("{smtp},{}", tls.addr().port());
        let rec = scan(
            d.path(),
            &[
                "--tls",
                "--targets",
                "127.0.0.1",
                "--ports",
                &ports,
                "--seed",
                "6",
            ],
        );
        install("banner-tls", &rec);
    }

    // 9–10. Interrupted, then resumed from its remainder.
    {
        let d = tempfile::tempdir().unwrap();
        let ports = format!("{open1},{closed1},80,443,8080,9090");
        let mut child = Command::new(BIN)
            .args([
                "run",
                "--output-dir",
                "out",
                "-q",
                "--targets",
                "127.0.0.1,192.0.2.1,192.0.2.2",
                "--ports",
                &ports,
                "--all",
                "--concurrency",
                "2",
                "--connect-timeout",
                "2s",
                "--seed",
                "7",
                "--no-spans",
            ])
            .current_dir(d.path())
            .env("NO_COLOR", "1")
            .env("XDG_CONFIG_HOME", d.path().join(".xdg"))
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .spawn()
            .unwrap();
        std::thread::sleep(Duration::from_millis(1500));
        // SAFETY-free: `kill` is a plain libc call on a pid this test just spawned.
        #[allow(unsafe_code)]
        unsafe {
            libc::kill(child.id() as i32, libc::SIGINT);
        }
        let status = child.wait().unwrap();
        assert_eq!(status.code(), Some(130), "an interrupted scan exits 130");
        let interrupted = record_in(&d.path().join("out"));
        let idir = install("interrupted", &interrupted);

        // Resume from the corpus copy, which is what an operator would do.
        let rem = read(&idir, &["output", "remainder"]);
        assert_eq!(code(&rem), 0, "{}", err(&rem));
        assert!(out(&rem).contains("# resumed-from:"), "{}", out(&rem));
        let d2 = tempfile::tempdir().unwrap();
        std::fs::write(d2.path().join("pairs.txt"), out(&rem)).unwrap();
        let rec = scan(
            d2.path(),
            &[
                "--pairs",
                "pairs.txt",
                "--all",
                "--connect-timeout",
                "1s",
                "--seed",
                "8",
            ],
        );
        install("resumed", &rec);
    }

    // 11. A record written by the 0.2.2 release binary (schema_version 1).
    match std::env::var("SCANR_COMPAT_BIN_0_2_2") {
        Ok(old) => {
            let d = tempfile::tempdir().unwrap();
            let o = run_with(
                &old,
                d.path(),
                &[
                    "run",
                    "--output-dir",
                    "out",
                    "-q",
                    "--targets",
                    "127.0.0.1,192.0.2.1",
                    "--ports",
                    &mixed_ports,
                    "--all",
                    "--connect-timeout",
                    "1s",
                    "--seed",
                    "9",
                ],
            );
            assert!(o.status.success(), "0.2.2: {}", err(&o));
            let rec = record_in(&d.path().join("out"));
            install("v1-0.2.2", &rec);
        }
        Err(_) => eprintln!("SCANR_COMPAT_BIN_0_2_2 unset; keeping the committed v1 record"),
    }

    // Config templates: one per release that has a binary, plus this build.
    for (var, version) in [
        ("SCANR_COMPAT_BIN_0_2_2", "0.2.2"),
        ("SCANR_COMPAT_BIN_0_3_0", "0.3.0"),
        ("SCANR_COMPAT_BIN_0_4_0", "0.4.0"),
    ] {
        if let Ok(old) = std::env::var(var) {
            let d = tempfile::tempdir().unwrap();
            let o = run_with(&old, d.path(), &["config", "init"]);
            assert!(o.status.success(), "{version} config init: {}", err(&o));
            std::fs::copy(
                d.path().join("scanr.toml"),
                corpus()
                    .join("configs")
                    .join(format!("scanr-{version}.toml")),
            )
            .unwrap();
        }
    }
    let d = tempfile::tempdir().unwrap();
    let o = run(d.path(), &["config", "init"]);
    assert!(o.status.success());
    let current = env!("CARGO_PKG_VERSION");
    std::fs::copy(
        d.path().join("scanr.toml"),
        corpus()
            .join("configs")
            .join(format!("scanr-{current}.toml")),
    )
    .unwrap();

    // The README, from the table.
    let mut readme = String::from(
        "# Compatibility corpus\n\nOne record per product workflow, the exact output every reader must produce for it\n(`expected/`), and the `config init` template of every release (`configs/`).\n`tests/compat.rs` holds the current binary to all of it; `docs/stability.md` is the\npromise it checks. Regenerate with the command in `tests/compat.rs` and review the diff.\n\n| scenario | proves |\n|---|---|\n",
    );
    for (name, claim) in SCENARIOS {
        readme.push_str(&format!("| `{name}` | {claim} |\n"));
    }
    readme.push_str("\nReaders pinned per scenario: ");
    readme.push_str(
        &READERS
            .iter()
            .map(|(n, _)| format!("`{n}`"))
            .collect::<Vec<_>>()
            .join(", "),
    );
    readme.push('\n');
    std::fs::write(corpus().join("README.md"), readme).unwrap();
}
