http_port 127.0.0.1:3128
acl localnet src 127.0.0.0/8
acl SSL_ports port 1-65535
acl Safe_ports port 1-65535
http_access allow localnet
http_access deny all
cache deny all
access_log none
cache_log /dev/stderr
pid_filename none
connect_timeout 2 seconds
